### ISSUE TITLE
document relation with existing python artifactory library: artifactory

### ISSUE THREAD

**Issue by ssbarnea** [tedops/party#3]
It would be great if you could document the differences between this libary and the other existing one named Artifactory. I raised a similar request against it too at https://github.com/Parallels/artifactory/issues/31

How do they compare, pros, cons, maybe policy regarding accepting contributions.

I am asking this because I do want to pick one and probably I will want to contribute to it and I want to make a good pick and not having to maintain my own fork. As a side not, on open-source world is good to document about "competition" :)

**Comment by tedops** [comment]
Hi Sorin,

Thanks for your interest in Party. I created it out of a need to
programmatically interact with the Artifactory API, and none existed at the
time that fit what I was looking for.

Party was intended to be a lightweight client that covered the Artifactory
API endpoints I use most, with more endpoint handlers added as needed
(either through my own work or PRs). I want to say that the difference
between it and the Parallel's project is akin to the one between Flask and
Django, but I would need to be more familiar with theirs to make that
analogy concrete.

Being able to create something that people find useful, while also giving
back to the open source community, is very rewarding to me. So, rather than
create arbitrary competition with Parallel's client, I will leave it to you
to decide which of the tools best fits your needs, since you know best the
details of your situation.

Thanks again!
